applications:
  app1:
    type: 'golang:1.22'
    source:
      root: 'app'

    relationships:
      db: 'db:mysql'

    hooks:
      build: |
        go build -o bin/app .

    web:
      upstream:
        socket_family: tcp
        protocol: http
      commands:
        start: ./bin/app
      locations:
        '/':
          allow: false
          passthru: true

services:
  db:
    type: mariadb:11.4

routes:
  "https://{default}/":
    type: upstream
    upstream: "app1:http"