applications:
  app1:
    type: 'golang:1.22'
    source:
      root: 'app1'

    hooks:
      build: |
        go build -o bin/app .

    web:
      upstream:
        socket_family: tcp
        protocol: http
      commands:
        start: ./bin/app
      locations:
        '/':
          allow: false
          passthru: true

  app2:
    type: 'golang:1.22'
    source:
      root: 'app2'

    hooks:
      build: |
        go build -o bin/app .

    web:
      upstream:
        socket_family: tcp
        protocol: http
      commands:
        start: ./bin/app
      locations:
        '/':
          allow: false
          passthru: true

  app3:
    type: 'golang:1.22'
    source:
      root: 'app3'

    hooks:
      build: |
        go build -o bin/app .

    web:
      upstream:
        socket_family: tcp
        protocol: http
      commands:
        start: ./bin/app
      locations:
        '/':
          allow: false
          passthru: true

  app4:
    type: 'golang:1.22'
    source:
      root: 'app4'

    hooks:
      build: |
        go build -o bin/app .

    web:
      upstream:
        socket_family: tcp
        protocol: http
      commands:
        start: ./bin/app
      locations:
        '/':
          allow: false
          passthru: true

routes:
  "https://{default}/":
    type: upstream
    upstream: "app1:http"

  "https://app2.{default}/":
    type: upstream
    upstream: "app2:http"

  "https://app3.{default}/":
    type: upstream
    upstream: "app3:http"

  "https://app4.{default}/":
    type: upstream
    upstream: "app4:http"
